### ISSUE TITLE
libaes70.cpp

### ISSUE THREAD

**Issue by Shurehon** [DeutscheSoft/AES70.js#10]
Hello, I found relevant information through this website “http://docs.deuso.de/libaes70.cpp/”. I would like to use the libaes70 library, but after reviewing this document, I did not find it. Can you tell me how to find this c++library? Thank you very much

**Comment by mattcph** [comment]
Hello,
libaes70.cpp is a commercial license software available at DeusO, you are welcome to reach out to them using the website contact info, https://deuso.de/impressum/
