### ISSUE TITLE
How to trigger AmpPreset d&b amp

### ISSUE THREAD

**Issue by AlexK-99** [DeutscheSoft/AES70.js#11]
Hi I would like to trigger the preset of a d&b amplifier with the help of your depandeny but I don't know what to do.
I have found out that it is an OcaAgent with the ONo: 10003 but unfortunately neither AES70Exploer nor my test code shows any further elements. I have been able to pick up the following OCA packet with the help of WireShark and d&b R1:

3b 00 01 00 00 00 00 1b 01 00 01 00 00 00 00 12 00 00 00 0010 01 4f 00 00 27 13 00 03 00 03 01 01 01
![OCA](https://github.com/user-attachments/assets/e9a1ccfe-7d2d-42cc-8f27-9c5bc268304b)

Now to the question how can I do this with the help of the Aes70 Lib

Thanks in advance

Alex

**Comment by arneg** [comment]
Hi Alex,

the basic strategy would be to create a custom class definition using [define_custom_class.js](https://github.com/DeutscheSoft/AES70.js/blob/master/src/controller/define_custom_class.js) to implement the db preset agent.

We have actually also run into this with d&b devices and were planning to do just that. I will look into publishing that definition once we have created it.

Arne

**Comment by AlexK-99** [comment]
@arneg Thanks for the quick reply. I got it working with the help of [define_custom_class.js](https://github.com/DeutscheSoft/AES70.js/blob/master/src/controller/define_custom_class.js)

Issue can be closed!

**Comment by arneg** [comment]
@AlexK-99 

Thats great! If you can maybe you could share that at some point. This might be useful for other users.

**Comment by AlexK-99** [comment]
Yes, I can share it. I used it in my code for my companion module. [amp-preset.js](https://github.com/AlexK-99/companion-module-d-und-b-amps/blob/main/amp-presets.js)
