### ISSUE TITLE
How to create an OCA device containing such as ”ocagain” object

### ISSUE THREAD

**Issue by Shurehon** [DeutscheSoft/AES70.js#12]
Hello, 
        first of all, thank you very much for providing the code. I have successfully controlled the attribute of setgain and getgain for online OCA devices through aes70.js. This is an important breakthrough for me. I would like to use this simple example to familiarize myself with the interaction between them. But the OCA device is also an important part, and I feel confused about it now. I ran the OCALite.cpp file, but only obtained the Ocp1LiteNetwork object through the controller. I want to know how to add a such  as  “ocagain”  object function to the OCA device in the OCALite project and hope to be able to communicate with this device in aes70.js for “setgain“ and “getgain”. Can you provide me with a simple example or a rough process? Thank you very much!

**Comment by arneg** [comment]
I am myself not familiar with the OcaLite code. Were you able to build the oca lite project and get a device up and running. Does it show up correctly in aes70explorer?

**Comment by Shurehon** [comment]
Thank you very much for your reply. I successfully built the ocalite vs project and ran ocalite.cpp. However, in the aes70explorer, the Ocp1LiteNetwork/OcaNetwork object appears below the device name on the left side, and some device information such as the device manufacturer is displayed in the lower right corner. I don't know if this is the result of running this project. Other features may need to be added by myself

**Comment by arneg** [comment]
Yes, I think additional objects might have to be added by you. I have never used OcaMicro myself, so maybe it would be best to ask over at https://github.com/OCAAlliance/OcaToolsAndDemos/

**Comment by Shurehon** [comment]
Ok, thank you very much for your reply. I'll go take a look

**Comment by Shurehon** [comment]
Another question is, if it's sending a multicast stream between two devices, how should I control them as receivers or senders, or when should I join and exit the group? What kind of class or objects should I use to control the stream? Can you provide a simple example or rough process

**Comment by arneg** [comment]
I think this is more of a high-level question and this is probably not the right forum for this. Are you or your employer member of the OcaAlliance? There is a technical mailing list which is a good place to have these things discussed.

**Comment by Shurehon** [comment]
Okay,  Thanks a lot for your reply.
Best wishes！
