### ISSUE TITLE
comment typo

### ISSUE THREAD

**Issue by andrew-elder** [DeutscheSoft/AES70.js#2]
Here https://github.com/DeutscheSoft/AES70.js/blob/master/src/Types.js#L125

**Comment by dbrignoli** [comment]
@andrew-elder, the typo is from the standard's XMI doc and ended up in this file because it is automatically generated. The same "Generic 32 bit float" doc string is also repeated for the OcaBoolean type. I wonder if there is a place where we can report these kind of issues.

**Comment by arneg** [comment]
Thanks for reporting it. I can forward these comments to make sure they get fixed in upcoming standard versions.

**Comment by andrew-elder** [comment]
@arneg - thanks. Feel free to close this issue after the comments have been forwarded "upstream".
