### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by dnrelectronica** [DeutscheSoft/AES70.js#3]
Hi all,

I started with the AES70.js library and installed it succesfully with:

$> npm install aes70

After that i copy the example code from github and pasted it into index.js file.
Unfortunately i directly get an error as shown above in the titel of this new issue. 
Is this a bug? 

additional info:
- node: v10.15.3
- npm: v6.9.0

`const OCA = require('aes70');
const connection = await OCA.controller.TCP.connect({
    host: 'example.org',
    port: 65000,
});`

**Comment by arneg** [comment]
Hi!

await is not allowed on the top-level. You will have to wrap this into an async function and call that. Example:

```

const OCA = require('aes70');

async function run() {
  const connection = ...;
};

run(); // returns a Promise
```

**Comment by arneg** [comment]
I updated the README to be more clear. It now contains the code in one working example.
