### ISSUE TITLE
Example on how to subscribe to device events

### ISSUE THREAD

**Issue by jakemonton** [DeutscheSoft/AES70.js#8]
Hi, I am playing with AES70. I was trying to implement subscription to device events but to no avail. Can you please provide a simple subscription process? Thanks

**Comment by arneg** [comment]
Hi @jakemonton ,

take a look at issue #6 which contains example code. If you need an OCA device, we have some running online at https://aes70x.net/

Hope this helps,

Arne

**Comment by jakemonton** [comment]
Hi @arneg thanks for the swift response. The example helped me a lot. Thanks again. Another question, is there a way to auto discover devices that is connected on the same network? 

Jake

**Comment by arneg** [comment]
Normally aes70 devices are announced using mdns. See e.g. this code as an example for how to discover them

https://github.com/DeutscheSoft/aes70explorer/blob/master/src/nodejs/lib/discovery.js

**Comment by jakemonton** [comment]
Thanks @arneg saw this earlier. Cheers
