### ISSUE TITLE
Bug in remote_device.js when running get_role_map

### ISSUE THREAD

**Issue by AlexK-99** [DeutscheSoft/AES70.js#9]
Hi, I am playing with AES70. I want to control the AMP 5D from D&B Audio, but I noticed when I use the get_role_map function that there is an infinite loop. In the function tree_to_rolemap in the while loop line 79 remote_device.js . Is this a bug or is it supposed to be like this or am I doing something wrong.

Thanks in advance

Alex

**Comment by arneg** [comment]
You are right, this is a bug. The D&B amp seems to re-use role names for objects. The aes70 standard says that should be avoided and the handling in this library was faulty. Will fix that, thanks for the report.

**Comment by arneg** [comment]
Fixed in `1.5.2` release.
